config:
  chunk_store_config:
    max_look_back_period: 336h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
  limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 16

persistence:
  enabled: true
  size: 1Gi
  storageClassName: longhorn

service:
  type: NodePort
  nodePort: 30998

updateStrategy:
  type: OnDelete
