alertmanager:
  enabled: true
  strategy:
    type: Recreate
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: longhorn
server:
  enabled: true
  strategy:
    type: Recreate
  retention: 14d
  extraFlags:
    - web.enable-lifecycle
    - web.enable-admin-api
    - storage.tsdb.no-lockfile
    - storage.tsdb.wal-compression
    - storage.tsdb.retention.size=60GB
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m
  persistentVolume:
    enabled: true
    size: 64Gi
    storageClass: longhorn
  service:
    type: NodePort
    nodePort: 30999
pushgateway:
  enabled: true
  strategy:
    type: Recreate
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: longhorn
