alertmanager:
  enabled: true
  nameOverride: alertmanager
  strategy:
    type: Recreate
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

server:
  enabled: true
  nameOverride: prometheus
  strategy:
    type: Recreate
  retention: 14d
  extraFlags:
    - web.enable-lifecycle
    - web.enable-admin-api
    - storage.tsdb.no-lockfile
    - storage.tsdb.wal-compression
    - storage.tsdb.retention.size=60GB
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m
  persistentVolume:
    enabled: true
    size: 64Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
  service:
    type: NodePort
    nodePort: 30999

pushgateway:
  enabled: true
  nameOverride: pushgateway
  strategy:
    type: Recreate
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
