---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-arrowdemo-xyz
  namespace: monitoring-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.arrowdemo.xyz`)
    kind: Rule
    services:
    - name: grafana
      port: 80
  tls:
    certResolver: default

